const myName = "uday solanki";
let age =18;
let myclass ="bca-1st year";
console.log(myName,age ,myclass);
const bornyear = "2006";
const currentyear = "2025";
console.log(currentyear-bornyear);
let hindi =50;
let english =70;
let maths =59;
let sanskrit =70;
let buissness = 51;
let accounts =60;
console.log( (hindi+english+maths+sanskrit+buissness+accounts)/600*100);
var a =10;
var a = 20;
console.log(a);